# General Jekyll Config
pygments: true
url: http://urbit.org
lsi: false
exclude: [LICENSE, CNAME, README.md, .gitignore]
permalink: /:year/:month/:day/:title.html
 
# Theme customization - please change from the defaults!
theme:
  # Color for top bar, links, etc
  highlight_color: '#971223'

  # Profile links on the left sidebar, leave blank to ignore
  social:
    github: urbit 
    twitter: Urbit_
    hacker_news: urbit

  # "Hi, I'm _______"
  name: Urbit
  email: urbit@urbit.org
  tagline: "An operating function"

  # Google Analytics key, leave blank to ignore
  google_analytics_key: UA-xxxx-x

  # Toggle "Postings are my own" disclaimer in footer
  show_disclaimer: false

authors:
  cgy:
    display_name: ~tasfyn-partyv [Curtis Yarvin]
    email: curtis@urbit.org
    github: cgyarvin

  jcb:
    display_name: ~tomsyt-balsen [John Burnham]
    email: john@urbit.org
    github: johncburnham
